# Generated by Django 5.0.6 on 2024-10-15 10:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('APP', '0005_staff'),
    ]

    operations = [
        migrations.CreateModel(
            name='Subject',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='APP.course')),
                ('staff', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='APP.staff')),
            ],
        ),
    ]
